name: Yeni bir Texturepack Oluştur
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "TerslenK"
        git config --global user.email "terslenkhd@gmail.com"
        git config pull.rebase false
        git pull
        rm -f texturepack.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'texturepack.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "Yeni Texturepack Oluştur"
        git push --force
